spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Employee_management_system?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  application:
    name: employee-management-system
file:
  path:
    profileImage: C:/Users/vidur/OneDrive/Documents/WorkingDirectory/FileStorageSystem/
    reports: C:/Users/vidur/OneDrive/Documents/WorkingDirectory/Reports/
server:
  port: 8082