eureka:
  instance:
    hostname: localhost
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:

        - id: login-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/login

        - id: register-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employee
            - Method=POST

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employee/**
          filters:
            - AuthenticationFilter